# app/config/routing.yml

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

# On inclut également les routes de notre CoreBundle, sans préfixe
oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"

login:
    pattern:   /login
    defaults:  { _controller: OCUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout
