# src/OC/PlatformBundle/Resources/config/routing.yml

oc_platform_home:
    path:      /{page}
    defaults:  { _controller: OCPlatformBundle:Advert:index, page: 1 }
    requirements:
        page: \d*

oc_platform_test:
    path:      /test
    defaults:  { _controller: OCPlatformBundle:Advert:test}

oc_platform_view:
    path:      /advert/{advert_id}
    defaults:  { _controller: OCPlatformBundle:Advert:view }
    requirements:
        advert_id: \d+

oc_platform_purge:
    path:      /purge/{days}
    defaults:  { _controller: OCPlatformBundle:Advert:purge }
    requirements:
        days: \d+

oc_platform_view_slug:
    path:      /{year}/{slug}.{_format}
    defaults:  { _controller: OCPlatformBundle:Advert:viewSlug, _format: html }
    requirements:
        year:   \d{4}
        format: html|xml

oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:      /edit/{advert_id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }
    requirements:
        advert_id: \d+

oc_platform_delete:
    path:      /delete/{advert_id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }
    requirements:
        advert_id: \d+

oc_platform_paramconverter:
    path: /test/{json}
    defaults: { _controller: "OCPlatformBundle:Advert:ParamConverter" }

