# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.advert_purger:
        class: OC\PlatformBundle\Purger\AdvertPurger
        arguments:  [@doctrine.orm.entity_manager]
