# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.advert_purger:
        class: OC\PlatformBundle\Purger\AdvertPurger
        arguments:  [@doctrine.orm.entity_manager]
    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, %locale%, 50]
        tags:
            -  { name: twig.extension }
    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML
    oc_platform.beta.listener:
        class: OC\PlatformBundle\Beta\BetaListener
        arguments: [@oc_platform.beta.html, "2015-05-31"]
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: processBeta }
    oc_platform.json_paramconverter:
        class: OC\PlatformBundle\ParamConverter\JsonParamConverter
        tags:
            - { name: request.param_converter }
