<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends EntityRepository
{
	public function deleteAdvertSkill($id)
	{
		$qb = $this->createQueryBuilder('a');

		$qb->delete()
		  ->where('a.advert = :id')
		  ->setParameter('id', $id)
		;

		return $qb
	      ->getQuery()
	      ->getResult()
	    ;
	}
}
